export const SET_ACCELEROMETER = 'SET_ACCELEROMETER'
export const SET_GYROSCOPE = 'SET_GYROSCOPE'
export const SET_ORIENTATION = 'SET_ORIENTATION'
export const SET_IMU = 'SET_IMU'

export const MYO_CONNECT = 'MYO_CONNECT'
export const MYO_DISCONNECT = 'MYO_DISCONNECT'
export const START_RECORDING = 'START_RECORDING'
export const STOP_RECORDING = 'STOP_RECORDING'

export const SAVE_VECTORS_TO_BUFFER = 'SAVE_VECTORS_TO_BUFFER'
export const SEND_BUFFER_TO_RECORDED = 'SEND_BUFFER_TO_RECORDED'

export const SENSORS_SELECT_ALL = 'SENSORS_SELECT_ALL'
export const SENSORS_DESELECT_ALL = 'SENSORS_DESELECT_ALL'
export const TOGGLE_SENSORS_SELECT_ACCELEROMETER = 'TOGGLE_SENSORS_SELECT_ACCELEROMETER'
export const TOGGLE_SENSORS_SELECT_GYROSCOPE = 'TOGGLE_SENSORS_SELECT_GYROSCOPE'
export const TOGGLE_SENSORS_SELECT_ORIENTATION = 'TOGGLE_SENSORS_SELECT_ORIENTATION'

export const SAVE_GESTURE = 'SAVE_GESTURE'
export const SET_GESTURE_NAME = 'SET_GESTURE_NAME'

export const SET_INTERFACE_MODE_NORMALBLANK = 'SET_INTERFACE_MODE_NORMALBLANK'
export const SET_INTERFACE_ADD_EDIT = 'SET_INTERFACE_ADD_EDIT'
export const SET_INTERFACE_RUN_COMPARE = 'SET_INTERFACE_RUN_COMPARE'
